name: Rust CI
on:
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Suite
    runs-on: buildjet-16vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      # The `rust-toolchain.toml` file dictates which version of rust to setup.
      - name: check rust version
        run: rustc --version

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Load rust cache
        uses: astriaorg/buildjet-rust-cache@v2.5.1

      - name: Run cargo check, failing on warnings
        run: cargo check --release --all-targets
        env:
          # The `-D warnings` option causes an error on warnings.
          RUSTFLAGS: "-D warnings"

      # If a dependency was modified, Cargo.lock may flap if not committed.
      - name: Check for diffs
        shell: bash
        run: |
          s="$(git status --porcelain)"
          if [[ -n "$s" ]]; then
              echo "ERROR: found modified files that should be committed:"
              echo "$s"
              git diff | head -n 128
              exit 1
          else
              echo "OK: no uncommitted changes detected"
          fi

      - name: Run tests with nextest
        run: cargo nextest run --release
        env:
          CARGO_TERM_COLOR: always

  fmt:
    name: Rustfmt
    runs-on: buildjet-8vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
        with:
          # we don't need lfs for the check to pass, but we do need it for the paths-ignore
          # option to work correctly.
          lfs: true
      - name: Load rust cache
        uses: astriaorg/buildjet-rust-cache@v2.5.1
      - run: cargo fmt --all -- --check
