name: Rust
on:
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: tests
    runs-on: buildjet-16vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v30

      - name: Setup Nix Cache
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.nix', 'flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          backend: buildjet

      - name: Pre-build development shell
        run: nix develop --command echo "devshell built and cached"

      - name: Run cargo check, failing on warnings
        run: nix develop --command just check

      # If a dependency was modified, Cargo.lock may flap if not committed.
      - name: Check for diffs
        shell: bash
        run: |
          s="$(git status --porcelain)"
          if [[ -n "$s" ]]; then
              echo "ERROR: found modified files that should be committed:"
              echo "$s"
              git diff | head -n 128
              exit 1
          else
              echo "OK: no uncommitted changes detected"
          fi

      - name: Run tests with nextest
        run: nix develop --command just integration
        env:
          CARGO_TERM_COLOR: always
